steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest',
      '.'
    ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest'
    ]

  # Step 3: Deploy to GKE by restarting the deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'rollout', 'restart', 'deployment/my-node-app',
        '--namespace=stage-id'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=stage-cluster'

images:
  - 'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY

