steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest'
    ]

  # Authenticate to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials stage-cluster --region asia-southeast2 --project carbay-indo

  # Apply the k8s deployment files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f k8s/ --namespace=stage-id

images:
  - 'asia-southeast2-docker.pkg.dev/carbay-indo/my-docker-repo/my-node-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY

